_BASE_: "../Base-RCNN.yaml"
MODEL:
  META_ARCHITECTURE: "FsodRCNN"
  ROI_HEADS:
    DROPOUT: 0.8
    NAME: "FsodRes5ROIHeads"
    NUM_CLASSES: 20
  CALIBRATE: true
  REFINE:
    MOMENTUM: 0.1
    NUM_CLASSES: 24
SOLVER:
  BACKBONE_LR_FACTOR: 0.01
  BASE_LR: 0.01
  STEPS: null
  MAX_ITER: null
  WARMUP_ITERS: 0
INPUT:
  MIN_SIZE_TRAIN: (384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024, 1056, 1088, 1120, 1152, 1184, 1216, 1248, 1280, 1312)
  MIN_SIZE_TEST: 800
