MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: false
  BACKBONE:
    FREEZE_AT: 3
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: false
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_BOX_HEAD:
    POOLER_RESOLUTION : 7
  ROI_HEADS:
    NAME: "Res5ROIHeads"
DATASETS:
  TRAIN: null
  TEST: null
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (85000, 100000)
  MAX_ITER: 110000
  CHECKPOINT_PERIOD: 1000000
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  WEIGHT_DECAY: 5.0e-5
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
VERSION: 2